version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    container_name: keycloak
    environment:
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HTTP_ENABLED: "true"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      DEBUG: "true"
      DEBUG_PORT: "*:5005"
    command: ["start-dev", "--auto-build"]
    ports:
      - 8081:8080
      - 5005:5005
    volumes:
      - ./target/keycloak-custom-attribute-idp-linking-2.1.1-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-custom-attribute-idp-linking-2.1.1-SNAPSHOT.jar
      # if you want to import a realm or some other things
      # - ./import/something.json:/opt/keycloak/data/import/something.json